# NumPy and Pandas - Crucial Tools for Data Scientists

When it comes to scientific computing and data science, two key python packages that are often used are NumPy and pandas. NumPy is a powerful python library that expands Python's functionality by allowing users to create multi-dimenional array objects (ndarray). In addition to the creation of ndarray objects, NumPy provides a large set of mathematical functions that can operate quickly on the entries of the ndarray objects without the need of for loops. Below is an example of the usage of NumPy. The code creates a random array and calculates the cosine for each entry in the array.

In [3]:
import numpy as np

X = np.random.random((4, 2))  # create random 4x2 array
y = np.cos(X)                 # take the cosine on each entry of X

print y

[[ 0.99782167  0.71935611]
 [ 0.99182799  0.90750689]
 [ 0.76811334  0.88994394]
 [ 0.96423103  0.99989573]]


We can easily access entries of an array, calling upon individual elements, and select of rows and columns.

In [10]:
print y[0, :]   # select 1st row
print y[:, 1]   # select 1st column
print y[2, 1]   # select element y_12
print y[1:2, :] # select rows 2nd and 3rd row

[ 0.99782167  0.71935611]
[ 0.71935611  0.90750689  0.88994394  0.99989573]
0.889943943301
[[ 0.99182799  0.90750689]]


The pandas (PANel + DAta) Python library allows for easy and fast data analysis and manipulation tools by providing numerical tables and time series data structures called DataFrame and Series, respectively. pandas was created to do the following:

- provide data structures that can handle both time and non-time series data
- allow mathematical operations on the data structures, ignoring the metadata of the data structures
- relational operations like those found in programming languages like SQL (join, group by, etc.)
- able to handle missing data

Below is an example of the usage of pandas and some of its capabilitites.

In [40]:
import pandas as pd

states = ['Texas', 'Rhode Island', 'Nebraska'] # strings
population = [27.86E6, 1.06E6, 1.91E6]         # float
electoral_votes = [38, 3, 5]                   # integer
is_west_of_MS = [True, False, True]            # boolean

# create and display DataFrame
dict_data = {'State': states, 'Population': population, 'West of Mississippi': is_west_of_MS, 'Electoral Votes': electoral_votes}
df1 = pd.DataFrame(dict_data)
df1

Electoral Votes  Population         State  West of Mississippi
0               38  27860000.0         Texas                 True
1                3   1060000.0  Rhode Island                False
2                5   1910000.0      Nebraska                 True

In the above code, we created a pandas DataFrame object, a tabular data structure that resembles a spreadsheet, similar to Excel. For those familiar with SQL, you can view a DataFrame as a SQL table.

The DataFrame we created consists of three columns, each with entries of different data types (integer, float, and string). It is built on top of NumPy, relying on ndarray and its fast and efficient arrays-based mathematical functions. For example, if we wanted to calculated the mean population across the states, we can run

In [20]:
print df1['Population'].mean()

10276666.6667


pandas relies on NumPy data types for the entries in the DataFrame. Printing the types of individual entries (using iloc to access entries via its index) shows

In [39]:
print type(df1['Electoral Votes'].iloc[0])
print type(df1['Population'].iloc[0])
print type(df1['West of Mississipi'].iloc[0])

<type 'numpy.int64'>
<type 'numpy.float64'>
<type 'numpy.bool_'>


Another example of the pandas and NumPy compatibility is if we have a DataFrame that is composed of purely numerica data we can apply NumPy functions. For example,

In [33]:
df2 = pd.DataFrame({"times": [1.0, 2.0, 3.0, 4.0], "more times": [5.0, 6.0, 7.0, 8.0]})
df2 = np.cos(df2)
df2.head()

more times     times
0    0.283662  0.540302
1    0.960170 -0.416147
2    0.753902 -0.989992
3   -0.145500 -0.653644

Acessing columns is inuitive, return the pandas Series object.

In [29]:
print df['Population']
print type(df['Population'])

0    27860000.0
1     1060000.0
2     1910000.0
Name: Population, dtype: float64
<class 'pandas.core.series.Series'>


A DataFrame object is composed of multiple Series, as illustrated above. The DataFrame class resembles a collection NumPy arraies but with labeled axes and mixed data types across the columns. In fact, Series is subclass of NumPy's ndarray.

## How Memory is configured in NumPy

The power of NumPy comes from ndarray object and how it's laid out in memory. The ndarray object consists of

- the data type of the entires of the array
- a pointer to a contiguous block of memory where the data/entries of the array reside
- a tuple of the array's shape
- a tuple of the array's stride

The shape refers to the dimension of the array while the stride refers the number of bytes to step in a particular dimension when traversing an array in memory. With both the stride and the shape, NumPy has sufficient information to access the array's entries in memory.

By default, NumPy arranges the data in row-major order, like in C. Row-major order lays out the entries of the array by groupings of rows. An alternative odering is the column-major ordering, as used in Fortran and MATLAB, which uses columns as the grouping. NumPy is capable of implementing both ordering schemes by passing the keyword 'order' when creating an array. See the figure below for the differeneces in the schemes.

<img src='figures/row_column_ordering.png'>

The continguous memory layout allows NumPy to use vector processors in modern CPU and array computations are efficient because NumPy can loop through the entries in data properly by knowing the location in memory and the data type of the entries. Further, NumPy can link to established and highly optimized linear algebra libraries like BLAS and LAPACK. As you can see, using the NumPy ndarray offers more efficient and fast computations over using the native Python list. No wonder pandas and other python libraries are built on top of NumPy.

However, the infrastructure of the ndarray object must require all entries be of the same data type, something that a python list is not limited to.

## Non-homogeneous Data Types in pandas